language: node_js
node_js:
  - 'node'
env:
  - EXTENSION_ID=hlepfoohegkhhmjieoechaddaejaokhf
deploy:
  provider: script
  skip_cleanup: true
  script: npm run release
  on:
    # Condition is set to deploy on: tags OR cron on master with recent commits
    condition: $(npm run can-release --silent)
